server:
  port: 9000

spring:
  application:
    name: apigateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
      - id: product
        uri: lb://product
        predicates:
          - Path=/api/v1/product/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
