server:
  port: 9091

spring:
  application:
    name: fake_product
  datasource:
    url: jdbc:postgresql://localhost:5432/fake_product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



